AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Loan Procurement Lambda for Bank of Prazy
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.bop.LoanApplicationLambda::handleRequest
      Runtime: java8
      CodeUri: target/bop-loan-lambdas-0.0.1-SNAPSHOT.jar
      Events:
        LoanProcurementAPI:
          Type: Api
          Properties:
            Path: /loan/procurement
            Method: POST