package com.bop.loan.beans;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="loanRequests")
public class LoanRequestDTO implements Serializable {

	private static final long serialVersionUID = 7526964358147809750L;

	private String userId;
	
	private String mobileNumber;
	
	private String loanType;
	
	private String loanAmount;
	
	private String termInYears;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="userId")
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@DynamoDBRangeKey(attributeName="mobileNumber")
	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	
	@DynamoDBAttribute(attributeName="loanType")
	public String getLoanType() {
		return loanType;
	}

	public void setLoanType(String loanType) {
		this.loanType = loanType;
	}
	
	@DynamoDBAttribute(attributeName="loanAmount")
	public String getLoanAmount() {
		return loanAmount;
	}

	public void setLoanAmount(String loanAmount) {
		this.loanAmount = loanAmount;
	}
	
	@DynamoDBAttribute(attributeName="termInYears")
	public String getTermInYears() {
		return termInYears;
	}

	public void setTermInYears(String termInYears) {
		this.termInYears = termInYears;
	}

	@Override
	public String toString() {
		return "LoanRequest [mobileNumber=" + mobileNumber + ", loanType=" + loanType + ", loanAmount=" + loanAmount
				+ ", termInYears=" + termInYears + "]";
	}
		
}
